import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SideNavbar from './components/SideNavbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SideNavbar/>
        <div className="w-full m-8 max-h-screen overflow-hidden overflow-scroll">
        {children}
        </div>
        </body>
    </html>
  )
}
